name: Task
on: push
jobs:
    job1:
        name: dateinshell
        runs-on: ubuntu-latest
        steps:
           - name: step1
             run: date

    job2: 
        name: dateinwindows
        runs-on: windows-latest
        steps:
          -  name: step1
             run: date
    job3:
        name: dateinmac
        runs-on: macos-latest
        steps:
          - name: step1
            run: date
    job4:
        name: dateindos
        runs-on: ubuntu-18.04
        needs: [job1, job2, job3] 
        steps:
          - name: step1
            run: date
    